version: "3"

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./packages/express-server/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
