pm2 deploy india --force 
pm2 deploy sydney --force 
pm2 deploy tokyo --force
pm2 deploy uae --force
pm2 deploy ireland --force
pm2 deploy brazil --force
pm2 deploy canada --force
pm2 deploy capetown --force
pm2 deploy frankfurt --force